### PR TITLE
Forward port of two kk4.4.3 patches

### PR DESCRIPTION
**Pull request by diegorondini**
This is a forward port of two kk4.4.3 patches, with modifications applied also to 'cnt'. Patches haven't been tested on l5.0.0, but they are trivial.

### CODE REVIEW

**Comment by gibsson** [comment]
Same as other pull request regarding the duplicates.
Regarding fstab, please remove the trailing spaces.
Thanks!

**Comment by diegorondini** [comment]
I added no trailing space (=space at the end) in fstab, if I'm not mistaken.
The added spaces (in the middle) are to maintain alignment of "wait".

**Comment by gibsson** [comment]
You're right, there's no trailing spaces, I guess I didn't look at it thoroughly. Feel free to send another version with the brightness set to false.
Thanks!

**Comment by diegorondini** [comment]
Updated version with automatic_brightness to false.

**Comment by gibsson** [comment]
Thanks again Diego !

**Pull request merged**
