### PR TITLE
common: build: fix dependencies for preboot build

### PR DESCRIPTION
**Pull request by grassead**
preboot image was not rebuilt after changes.

Signed-off-by: Adrien Grassein <adrien.grassein@smile.fr>

### CODE REVIEW

**Comment by gibsson** [comment]
Thanks Adrien!

**Comment by gibsson** [comment]
Hi Adrien,

Actually this patch breaks the build if $OUT/preboot doesn't exist. Do you happen to have a fix for it by any chance?

Thanks,
Gary

**Comment by grassead** [comment]
Hi, sorry for the delay, do you have a way to reproduce this issue?

I can rebuild he image from scratch without any issue (by using the imx-make.sh script).

Thanks;

**Comment by gibsson** [comment]
Yes, in my case this was failing:
rm -rf $OUT/preboot*
make -j16

Anyway, I reverted it as it was causing issues with our build server. I changed the preboot target to regenerate the img every build as it takes no time.

**Comment by grassead** [comment]
Ok. I will try to fix this, but lunch + make combo always cause an issue (before my patch as it always needs the kernel an u-boot to generate the final images).

I will try to fix it.

Thanks;

**Comment by grassead** [comment]
For example if I didn't build the kernel before Android I got this error:

"FAILED: ninja: 'out/target/product/nitrogen8mm/obj/KERNEL_OBJ/arch/arm64/boot/Image', needed by 'out/target/product/nitrogen8mm/kernel', missing and no known rule to make it"

I assume that the images are not building "from scratch" and that it's mandatory to use the imx-make.sh script.

**Pull request merged**
